name: flutter_text
description: A new Flutter application.
version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  event_bus: ^2.0.0
  mqtt_client: ^9.3.1
  drag_list: ^1.0.7
  flutter_slidable: ^0.5.4
  flutter_screenutil: ^0.5.2
  sliding_up_panel: ^0.3.6
  liquid_swipe: ^2.1.0
  shared_preferences: ^2.0.5
  image_picker: ^0.6.0+20
  curved_navigation_bar: ^0.3.2
  url_launcher: ^5.2.1
  local_auth: ^1.1.4
  provider: 5.0.0
  flutter_speed_dial: ^1.2.4
  simple_animations: 1.3.8
  google_sign_in: 4.0.12 #谷歌全家桶
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.0
  firebase_storage: ^3.0.10
  firebase_database: ^3.0.9
  firebase_core: 0.4.0+9
  http: ^0.13.1
  photo_view: ^0.4.2
  agora_rtc_engine: ^1.0.1
  video_player: ^2.1.1
  orientation: ^1.1.0
  common_utils: ^1.1.3
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  intl: ^0.17.0
  audioplayers: ^0.18.3
  image_picker_saver: ^0.3.0
  permission_handler: 3.0.0
  flutter_full_pdf_viewer: ^1.0.6
  flutter_staggered_animations: ^0.1.2
  qrscan: ^0.2.17 #二维码
  mini_calendar: ^0.3.1 #日历
  flutter_picker: ^1.1.4
  flutter_swiper: ^1.1.6
  inview_notifier_list: 1.0.0 #视频滚动到播放
  sentry: ^5.0.0  #日志监听
  connectivity: ^3.0.3
  image_gallery_saver: ^1.2.2
  flutter_plugin_record: ^1.0.1
  path_provider: ^2.0.1
  sqflite: ^1.3.1+1
  bot_toast: 4.0.0
  flutter_local_notifications: ^5.0.0+1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  wechat_assets_picker: ^5.5.3
  move_to_background: ^1.0.0
  lpinyin: ^1.0.9   # 汉字转拼音
#  flutter_doraemonkit:
#    path: C:\Users\coco\AndroidStudioProjects\flutter_doraemonkit
  get: ^4.1.4
  call: ^0.3.0
  flutter_intro: ^2.3.0
  ios_share:
    git: https://github.com/NayoLx/ios_share.git
  ota_update: ^3.0.2
  package_info: ^2.0.2
  postgres: ^2.3.2
  epubx: ^3.0.0-dev.3
  epub_view: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/111.png
    - images/timg.jpg
    - images/timg2.jpg
    - images/timg3.jpg
    - images/sun.jpg
    - images/plane1.gif
    - images/plane2.gif
    - images/oneday.gif
    - images/cloud3.gif
    - images/cloud2.gif
    - images/cloud1.gif
    - images/cloud5.gif
    - images/weather/
    - images/voice/
    - images/_cat_sky.jpg
    - assets/index.pdf
    - assets/long14.epub
    - assets/data/
    - assets/dll/

